### ISSUE TITLE
Cloudflare FULL mode

### ISSUE THREAD

**Issue by InfiniteCod3** [41Baloo/balooProxy#10]
Cloudflare breaks while being set on full mode and having the A record pointing to a server where this proxy is hosted.

**Comment by InfiniteCod3** [comment]
If the TLS mode is set to flexible it becomes fine

**Comment by 41Baloo** [comment]
as described in the ReadMe,

> If this field is set to true balooProxy will be in cloudflare mode. (NOTE: SSL/TLS encryption mode in your cloudflare settings has to be set to "Flexible". Enabeling this mode without using cloudflare will also not work. Additionally, some features, such as TLS-Fingerprinting will not work and always return "Cloudflare")
