### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by csirkepipi** [41Baloo/balooProxy#13]
Can I use cloudflare for balooProxy as a DNS manager without any proxies and protection from cloudflare and use the tls fingerprinting or using cloudflare in any way blocks the tls fingerprinting option?

**Comment by 41Baloo** [comment]
Yes. As long as the traffic to balooProxy is not proxied by another http proxy it should work fine

**Comment by csirkepipi** [comment]
Oh, okay, thanks.

best regards
Gergely

**Comment by csirkepipi** [comment]
Also, can I use cloudflare's SSL certificate?
