### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by nutria22** [41Baloo/balooProxy#19]
I am contacting you to ask for your help regarding a script that I have recently acquired. I would like to know if it would be possible for you to create a manual or a quick tutorial explaining how to make the script work properly.

**Comment by GamertjeNL** [comment]
Hi,

I got like the same "issue". I have the BalooProxy running on a VM on my PC just to test. Only right now i got a second VM running with nginx enabled with port 80 and a other VM with kali linux running to run some little Dos attacks. Only right now i got the problem that nothing is going through the proxy but it goes directly to the VM where the nginx has installed. How can i fix this that it goes through the proxy so it can block the bad traffic and the good traffic is going to the Nginx VM?

**Comment by 41Baloo** [comment]
Ill try to make the readme explain installation stepts better

**Comment by 41Baloo** [comment]
I hope the [latest commit](https://github.com/41Baloo/balooProxy/commit/95dffbd6ae20e5a2dc0faa3d483c3d5e3896abdb) cleared up most of the issues you had. I added more detailed installation stepts to [the Readme](https://github.com/41Baloo/balooProxy#installation)

![grafik](https://user-images.githubusercontent.com/73783549/230872945-cf57e51d-e983-43f9-a835-52c5567dca07.png)
