### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by LaAlexita** [41Baloo/balooProxy#22]
"adminsecret": "CHANGE_ME",
        "apisecret": "CHANGE_NE",
        "secrets": {
            "captcha": "CHANGE_ME1",
            "cookie": "CHANGE_ME2",
            "javascript": "CHANGE_ME3"
        },
        
       what I have to put in "change_me"?

**Comment by 41Baloo** [comment]
They are secret keys that allow the challenges to be validated without running a database which stores the validations for the challenges the visitors solved. As mentioned in https://github.com/41Baloo/balooProxy#secret-mapstringstring these should not be given to anyone else and ideally be generated with a tool such as https://www.random.org/strings/?num=1&len=20&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new. Alternatively you can just delete the config.json and the proxy will randomly generate secrets for you the first time you start it.
