### ISSUE TITLE
How to protect a localhost:8080 project

### ISSUE THREAD

**Issue by localuser-isback** [41Baloo/balooProxy#23]
lets say i had something running on localhost:8080 how would i use baloo to protect it?

**Comment by 41Baloo** [comment]
you should be able to proxy your localhost if you enter localhost:8080 in the config or any other loopback address

**Comment by localuser-isback** [comment]
Where specificly in the config since ive tried a lot and haven't got anything to work...

**Comment by localuser-isback** [comment]
may you give an example config for a localhost:8080 project

**Comment by 41Baloo** [comment]
`{
            "name": "example.com",
            "backend": "localhost:8080",
            "scheme": "http",
            ...
}`

Should work fine and forward port 80 and/or 443 to your localhost 8080

**Comment by IntelligenceHostingLLC** [comment]
@localuser-isback Use nginx or whatever http handler you are using and change the point to something like 1337 then localhost:1337 as the backend ip.
