### ISSUE TITLE
Discord Whitelist

### ISSUE THREAD

**Issue by KingJimmy12** [41Baloo/balooProxy#24]
Having some issues whitelisting discord user agent to allow for Embeds, Please may you help Thank u

**Comment by 41Baloo** [comment]
My appologies, there seemed to have been a typo in the way the firewall rules got evaluated. I pushed a commit that should allow http.user_agent to be used as a valid field now. If you pull that commit everything should work
![image](https://github.com/41Baloo/balooProxy/assets/73783549/84c4119b-255d-4918-b53f-30f365612e32)

**Comment by KingJimmy12** [comment]
Thanks :)
