### ISSUE TITLE
Admin Panel / Dashboard

### ISSUE THREAD

**Issue by GamertjeNL** [41Baloo/balooProxy#25]
Hi,

I see a html file with the name: login.html and if i look at the code, it looks like you was working on a dashboard or something? Is this still a WIP (Work in progress) or is this coming soon?

Thank u!

**Comment by 41Baloo** [comment]
I was experimenting with the thought. I haven't done much more than that tho. I might add it in the future or might not

**Comment by GamertjeNL** [comment]
Ok, i will check if i can add Prometheus / Grafana for my additional monitoring but i hope to see later the dashboard for the monitoring and more!
