### ISSUE TITLE
Not allowing a certain IP address to go through

### ISSUE THREAD

**Issue by itsunderscores** [41Baloo/balooProxy#26]
I'm trying to allow a certain IP to go through, but it's not working. I also tried adding a file to allow, and it still doesn't work.

```
"firewallRules": [
 {
"expression": "(ip.src eq 157.230.xx.xxx)",
"action": "0"
},
{
"expression": "(http.query contains \"0_link.php\")",
"action": "0"
},
]
```

What am I doing wrong?

**Comment by itsunderscores** [comment]
It keeps getting rate limited, anyway to bypass this?

**Comment by 41Baloo** [comment]
There isnt a way to bypass the ratelimit currently. As for your issue of whitelisting the ip, make sure you dont lock the proxy stage. Also try restarting the proxy after applying the changes to your config.json
