### ISSUE TITLE
R1 ratelimit; challenge requests

### ISSUE THREAD

**Issue by gang000** [41Baloo/balooProxy#29]
hi, sometime when i reload site it suddenly says Ratelimited (R1). But i didnt get the captcha or anything else.

**Comment by 41Baloo** [comment]
R1 means your client requested the challenge more often than defined in your config.json. There is a bug in the current release that might cause that, so i would suggest using the newest commit of the gofiber branch which can be found at https://github.com/41Baloo/balooProxy/blob/gofiber/main

**Comment by gang000** [comment]
> R1 means your client requested the challenge more often than defined in your config.json. There is a bug in the current release that might cause that, so i would suggest using the newest commit of the gofiber branch which can be found at https://github.com/41Baloo/balooProxy/blob/gofiber/main

In my current version, the cookies use Lax already, I have compiled the program myself

**Comment by gang000** [comment]
Also, because you need to add a cookie before each request, and the redirect the request, it creates a large redirect chain, i've checked my wesite and it redirected about 7 times.

**Comment by 41Baloo** [comment]
Given the browser is working correctly, it shouldnt have multiple redirects after one another. It should look like this:

- browser sends a request without the cookie set/correct cookie
- balooProxy responds with a "set-cookie" header, instructing the browser to set the cookie. the same response is a statuscode 307 and has a header of "location" that points to the same path & query the browser just refreshes
- All of this causes the browser to first set the cookie and then essentially "refreshing" by sending the request again, this time with the cookie
- the cookie is now set/correct and the browser gets the response from the origin server

If you can somehow reproduce a redirect chain of up to 7 redirects, feel free to send in here how you do it and ill try to fix it
