### ISSUE TITLE
Bunny.net CDN

### ISSUE THREAD

**Issue by OXALD** [41Baloo/balooProxy#31]
Could do Compatible with bunny.net ?

**Comment by 41Baloo** [comment]
I'm not familiar with bunny.net but you should be able to modify the cloudflare mode so it supports bunny instead.

To get the correct IP, changing [this line](https://github.com/41Baloo/balooProxy/blob/974efb3cf41d3f5d6d69b6e44e9f5fad9de99103/core/server/middleware.go#L53) should work. You'll just need to know how bunny.net provides the origin servers the client ip
