### ISSUE TITLE
Smarting Ratelimiting & HTTPs Support

### ISSUE THREAD

**Issue by DoYouKnowWhoElse** [41Baloo/balooProxy#34]
make cloudflare look like a joke

support https without me having to touch your code 😜

**Comment by 41Baloo** [comment]
I assume with "https" support you mean supporting https in cloudflare mode?
What exactly do you mean with "smart" ratelimit?

**Comment by 41Baloo** [comment]
might add https support while being in cloudflare mode soon. I don't think i'll ever work on a smart ratelimit on my own but feel free to open a PR
