### ISSUE TITLE
Discord Firewall rule not working / not applying

### ISSUE THREAD

**Issue by Catchii69** [41Baloo/balooProxy#35]
my firewall rules should be correct but i think they are not being applied

i tried restarting but does not work.

         "firewallRules":[
            {
               "expression": "(http.user_agent eq \"Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com/)\")",
               "action":"0"
            }
         ],

**Comment by 41Baloo** [comment]
As stated in the docs,

> [http.user_agent String](https://github.com/41Baloo/balooProxy#httpuser_agent-string)
Represents the user-agent sent by the client **(Important: will always be lowercase)**

the useragent will always be lowercased due to our implementation of the rules engine not having a "toLower" function. So your rule should look like this instead:

```
{
           "expression": "(http.user_agent eq \"mozilla/5.0 (compatible; discordbot/2.0; +https://discordapp.com/)\")",
           "action":"0"
}
```

**Comment by Catchii69** [comment]
hey, thanks for the answer. i have tried your code but it still wont work same error on discord embeds

Followed too many redirects (6)

i can see some requests going in but not being shown in the logs

**Comment by 41Baloo** [comment]
I've just checked.

```
{
                    "expression": "(http.user_agent eq \"mozilla/5.0 (compatible; discordbot/2.0; +https://discordapp.com)\")",
                    "action": "0"
}
```

Works fine for me. Make sure its first in the firewall rule chain. BalooProxy evaluates rules from top to bottom / from left to right. So if there's a rule before this whitelisting rule that e.g. applies a stage of 2, that rule will be used instead of this one

![grafik](https://github.com/41Baloo/balooProxy/assets/73783549/be74ee05-ef9a-457c-80fc-88e5efe51533)

**Comment by Catchii69** [comment]
Hey, i have only one firewall rule and it is the one for discord, heres the config for my domain

```
        {
            "name":"retards.lol",
            "backend":"localhost:8078",
            "scheme":"http",
            "certificate":"",
            "key":"",
            "webhook":{
                "url":"discordwh",
                "name":"retards.lol rel",
                "avatar":"",
                "attack_start_msg":"ono atack",
                "attack_stop_msg":"no atack woo"
            },
            "firewallRules":[
              {
                "expression": "(http.user_agent eq \"mozilla/5.0 (compatible; discordbot/2.0; +https://discordapp.com/)\")",
                "action":"0"
              }
            ],
            "bypassStage1":75,
            "bypassStage2":75,
            "disableBypassStage3":25,
            "disableRawStage3":5,
            "disableBypassStage2":3,
            "disableRawStage2":2
        }
    ]
}
```

**Comment by Catchii69** [comment]
oh my god i am so retarded

i did not see the slash at the end https://discordapp.com**/**

im so sorry 

it works perfectly now thanks
