### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by webmastermario** [41Baloo/balooProxy#36]
Hello,
 

i receive this error when accessing the direct IP: balooProxy: 13.40.118.187 does not exist. If you are the owner please check your config.json if you believe this is a mistake.
And when directly the domain its not working at all. What can i do? I create the config.json with /.main and its successfully loaded. I have entered SSL with cloudflare on and IP:port and the domain but its not wokring.

Any help?

**Comment by webmastermario** [comment]
Also proxied status is enabled on cloudflare?

**Comment by webmastermario** [comment]
inside when running ./main i receive no log etc.

**Comment by 41Baloo** [comment]
Are you screening the proxy, as in making sure it's running? Does the proxy have "cloudflare mode" enabled ("cloudflare" in the config.json). Is port 80 open on your server?

**Comment by webmastermario** [comment]
port 80 is open on both servers, but on the backend server it is set to 8080 and i also added this to the config.json (with IP:PORT). with command netstat -tuln | grep 80 on the frontend server i dont see it. could this be the reason?
cloudflare is also set to true in the config file.

**Comment by webmastermario** [comment]
i enable with ./main and telnet IP 80 and it is connecting.

**Comment by webmastermario** [comment]
i tried now to switch off cloudflare proxy and for https i receive "ERR_QUIC_PROTOCOL_ERROR" and for http i receive too many redirects and than blocked by balooProxy? what can i do to correct this?

**Comment by 41Baloo** [comment]
> port 80 is open on both servers, but on the backend server it is set to 8080 and i also added this to the config.json (with IP:PORT). with command netstat -tuln | grep 80 on the frontend server i dont see it. could this be the reason? cloudflare is also set to true in the config file.

If you start the proxy, it should listen on port 80 of the server you started it on. If it doesn't do that, maybe it doesn't have enough permissions to do that. Since you said, visiting the ip directly works tho, that shouldnt be an issue. Are you sure cloudflare points to the proxy ip and not your backend ip? If you can visit the ip directly, so should cloudflare, unless you maybe have iptables that block cloudflare from doing so
