### ISSUE TITLE
520 error when pending file upload request

### ISSUE THREAD

**Issue by hriiss** [41Baloo/balooProxy#37]
When I upload a file and the request is pending for like 5 seconds or longer, i get a 520 cloudflare error, the only issue i can think of this, that its because of balooproxy. I have tried setting all the timeout options to over 30 seconds, but it didnt help.

**Comment by 41Baloo** [comment]
Refeer to #32. This will be fixed when i update the main branch

**Comment by hriiss** [comment]
> Refeer to #32. This will be fixed when i update the main branch

Hello, thank you for the reply. What is the ETA for this? It's very important for my project.
Or maybe I can do this myself?

**Comment by hriiss** [comment]
> Refeer to #32. This will be fixed when i update the main branch

Another question, theoretically it would work to stream the files to a complete other api (e.g. with vercel), right?

**Comment by 41Baloo** [comment]
You could stream it through an endpoint that isnt protected by balooProxy 1.5 (e.g. 1.4), yes

**Comment by hriiss** [comment]
> You could stream it through an endpoint that isnt protected by balooProxy 1.5 (e.g. 1.4), yes

What do you mean by through? Stream it from or to an endpoint that isn't protected?

**Comment by hriiss** [comment]
> You could stream it through an endpoint that isnt protected by balooProxy 1.5 (e.g. 1.4), yes

Hello sorry for bothering,
I have downgraded to 1.4, it works better now, but when streaming big files 60MB+ it still crashes.

**Comment by 41Baloo** [comment]
Feel free to try the latest pre-release of the main branch. That should work better
