### ISSUE TITLE
Discord Alerts

### ISSUE THREAD

**Issue by dezegozer** [41Baloo/balooProxy#39]
Great reverse proxy! Only problem is that my discord alerts do not seem to be sending. Config is setup correctly and i have had attacks of 100k+ so it seems like there shoulda been some alerts. How would i fix this?

**Comment by 41Baloo** [comment]
Feel free to send a censored version of your config in here, ill take a look. Discord alerts should work

**Comment by n1xsec** [comment]
Pretty sure webhooks only send if the traffic is bypassing and reached the bypass threshold

**Comment by 41Baloo** [comment]
Depending on the version of the proxy you're using, that can be the case, yes. In 1.5 it also triggers on non-bypassing requests, if your threshold is exceeded tho

**Comment by LostInFame** [comment]
> Feel free to send a censored version of your config in here, ill take a look. Discord alerts should work

its default everything except discord webhook url and latest version, no notifs when any stage enables or sum or any ddos attack
