### ISSUE TITLE
enhancement: Some enhancement for balooproxy

### ISSUE THREAD

**Issue by UTrosh** [41Baloo/balooProxy#43]
Here is some enhancement : 

- Implement Redis pub/sub to update the configuration of each domain, similar to the approach used in this project: https://github.com/lhridder/infrared. This method leverages Redis for configuration storage and pub/sub for adding/deleting configurations. It's particularly beneficial for managing multiple proxy instances.

- Integrate Prometheus statistics for each domain, including metrics such as blocked requests, bypassed requests, and CPU usage.

- Improve Discord notifications by providing specific details on the type of attack detected, offering a more comprehensive insight into the events.

**Comment by 41Baloo** [comment]
- Might add support for redis in the future
- Prometheus implementation should be done via the api, to avoid load on the proxy
- balooProxy has no capabilities to detect the attack-type. We're simply challenging potential bots with more and more complex challenges to solve
