### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by MrEzerYT** [41Baloo/balooProxy#44]
pls guide for installation

**Comment by dnscat** [comment]
To install the latest main file on your server, follow these steps: 1) Download the latest main file.
2) Decide whether to run it in a screen.

If you choose to use a screen, enter 'screen -S [name]' and
then 'chmod +x main'.

3) Run the installation instructions by entering './main' or press enter repeatedly.
To ensure smooth operation, enable the Cloudflare addon if you are using Cloudflare.
After installation, locate the config.json file in the main file folder and add your backend IP address to the correct path. After installation, locate the config.json file in the main file folder and add your backend IP address to the correct path. Save the configuration and reload the monitor.
After installation, locate the config.json file in the main file folder and add your backend IP address to the correct path.
If the monitor still does not work, run ./main again.
If the issue persists, deactivate any web server installed on the server intended to be used as a Baloo proxy server, such as Apache, phpmyadmin, or nginx.


This will complete the process.
After deactivation, run ./main again, and the issue should be resolved.

Finally, add the Baloo proxy server as an A record to Cloudflare.
