### ISSUE TITLE
baloo 1.4 Works fine -- 1.5 Crashes on .tar.gz download

### ISSUE THREAD

**Issue by dehlirious** [41Baloo/balooProxy#46]
So, I've been using 1.4 with no issues. Matter of fact, I didn't realize I wasn't using the latest as the repository, excluding the releases section, only has the code for 1.4. (so git clone *repo url* only provides baloo 1.4 source)

On my web server, I'm unable to use baloo 1.5. I tried with my old config.json, no luck. Generated a new config.json, also no luck. It'll start just fine -- but as soon as I try to download a .tar.gz file , it consumes a lot of CPU and dies. No crash.log entries! 

I'd definitely enjoy using the latest and greatest, reap the performance benefits, but given that it's unusable, I can't. 

And given that no crash.log entries are generated, I can't easily diagnose it yet. I may dig into this myself-- we will see. For now, 1.4 is stable.

All that I'm aware of at the moment is:
It starts consuming 100% cpu, RAM usage rises to max (4gb in this instance, 4gb file trying to be downloaded) - then it says "Killed" -- which is likely why no crash.log entry is generated

Second issue:

Improper iframe srcdoc encoding in serve.go

Problem: iframe shows as a blank frame due to the contents of srcdoc not being htmlencoded.
Solution:

import "html" and change the iframe portion to:
```
<iframe width="100%" height="25%" style="border:1px ridge lightgrey; border-radius: 5px;"
srcdoc="
` + html.EscapeString(string(errBody)) + `">
</iframe>
```

**Comment by 41Baloo** [comment]
the source code for 1.5 is on the gofiber branch. Sadly gofiber doesnt support streaming, hence files will first be fully downloaded into the proxys ram, causing crashes if the files are too big

I have been debating if i want to port the changes i made in 1.5 to the main branch too but since they're pretty major and i havent really actively been working on this, i havent done so yet

Ill look into the iframe stuff, tho it's always worked for me

**Comment by 41Baloo** [comment]
https://github.com/41Baloo/balooProxy/tree/merge-gofiber-improvements (soon to be merged into main)

should now have the improvements of the gofiber branch. Sadly it's not possible to support streaming with gofiber, as it's only able to stream data itself but will still have to first download the stream from the backend completely (AFAIK)

**Comment by 41Baloo** [comment]
Merged into main now
