### ISSUE TITLE
I'm getting: invalid IP address

### ISSUE THREAD

**Issue by itsunderscores** [41Baloo/balooProxy#47]
In the crash.log I'm getting a weird error I've never gotten before, it only happens when an attack is placed against the server.

Error Loading Custom Firewall Rules
invalid IP address

**Comment by itsunderscores** [comment]
I'd also like to add, if the DDoS attack is big, the script shutsdown and I get: invalid memory address or nil pointer dereference

**Comment by 41Baloo** [comment]
Mind sending your custom firewall rules in here?
