### ISSUE TITLE
Petition to clean up the code?

### ISSUE THREAD

**Issue by dropout1337** [41Baloo/balooProxy#5]
This isn't python, you don't need everything in 1 file...

**Comment by 41Baloo** [comment]
this wasnt originally ment to be longer than a few 100 lines, hence the mess. thankfully pxzdano was kind enough to start cleaning the code. Will hopefully be done soon.

**Comment by lucynya** [comment]
pxzdano a qt fr

**Comment by 41Baloo** [comment]
Should hopefully be a lot more clean in the latest commit
