### ISSUE TITLE
Pre-release version - Killed

### ISSUE THREAD

**Issue by GergelyGombai** [41Baloo/balooProxy#60]
The proxy is getting "Killed" when the server receives a big attack, like 70-90k rps

**Comment by ToffyMTA** [comment]
Increase ulimit -n on your server

**Comment by 41Baloo** [comment]
That message is linux killing balooProxy because it consumes too much ram. If you have issues with that i'd suggest either using a bigger server or using the gofiber version, which uses a lot less ram.
