### ISSUE TITLE
Race Condition bug

### ISSUE THREAD

**Issue by Algo1337** [41Baloo/balooProxy#62]
This is suppose to run parrallel so you can parse connections faster. This is vuln to ddos.

https://github.com/41Baloo/balooProxy/blob/1ba331b98f44016c99c9a50ab544e742a0c328a8/core/server/monitor.go#L101

**Comment by Algo1337** [comment]
Changed title

**Comment by 41Baloo** [comment]
Not a race condition. Always ran in locked threads.

The only time this is used is inside of a locked thread. Please at least try to understand the code/language before opening chatgpt generated issues.

https://github.com/41Baloo/balooProxy/blob/1ba331b98f44016c99c9a50ab544e742a0c328a8/core/server/monitor.go#L88-L92
