### ISSUE TITLE
Reload not being automatically executed?

### ISSUE THREAD

**Issue by h1v9** [41Baloo/balooProxy#64]
The readme states as follow
`The command reload will cause the proxy to read the config.json again, aswell as reset some other generic settings, in order to apply changes from your config.json (NOTE: This is automatically executed every 5 hours)`

Specifically
`(NOTE: This is automatically executed every 5 hours)`

However, I couldn't find anywhere in the code where this happens. Is the readme wrong or am I missing something?

**Comment by 41Baloo** [comment]
That indeed seems to be a leftover and is no longer the case
