### ISSUE TITLE
#Help

### ISSUE THREAD

**Issue by Shishir-Talukdar** [41Baloo/balooProxy#8]
Bro can you share  installing processes, I can’t install.Can you share installation process step by step. If you share its helpful for us.

**Comment by lucynya** [comment]
..? you need to edit config.json & execute one file

**Comment by 41Baloo** [comment]
Read the ReadMe.md to understand how to configure the config.json or elaborate your problem in here more accurately, download the file from https://github.com/41Baloo/balooProxy/releases/tag/1.1 and just run it with

`./main`

**Comment by 41Baloo** [comment]
The latest commit should make it a lot easier to use
